
services:
  db:
    image: mysql:8.0
    container_name: paan-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
      MYSQL_DATABASE: panshop
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: ./paan-backend
    container_name: paan-backend
    ports:
      - "9090:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/panshop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysql123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql123
    depends_on:
      - db

volumes:
  mysql-data:
